//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT6DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Typesize
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Typesize()
        {
            this.Melts = new HashSet<Melt>();
        }
    
        public int id_typesize { get; set; }
        public System.DateTime tCreatedDate { get; set; }
        public string typesize1 { get; set; }
        public bool visible { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Melt> Melts { get; set; }
    }
}
