//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntervalsDBTypesLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interval
    {
        public int Id { get; set; }
        public string Object { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.TimeSpan Duration { get; set; }
        public int SpecialLevel { get; set; }
    }
}
