//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanerTubeInfoDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanerTubeInfo
    {
        public long id { get; set; }
        public System.DateTime Date { get; set; }
        public string Melt { get; set; }
        public string TubeNum { get; set; }
        public long TubeStatus { get; set; }
        public string TypeSize { get; set; }
        public string Standart { get; set; }
        public long Speed { get; set; }
        public long Length { get; set; }
    }
}
